services:
  nginx:
    image: nginx:latest
    container_name: smithery-2api-nginx
    restart: always
    ports:
      - "${NGINX_PORT:-8088}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - smithery-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smithery-2api-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - smithery-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  smithery-net:
    driver: bridge
